#!/usr/bin/bash

cd ~/
# install the latest node by checking the `setup_xx.x`
sudo apt update
sudo apt install curl dirmngr apt-transport-https lsb-release ca-certificates -y
curl -sL https://deb.nodesource.com/setup_19.x | sudo -E bash -

# alacritty
git clone https://github.com/alacritty/alacritty.git
cd alacritty
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source ~/.bashrc
rustup override set stable
rustup update stable
sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3 -y
cargo build --release --no-default-features --features=x11
sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
sudo cp target/release/alacritty /usr/local/bin
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database

# extra
sudo apt install openjdk-19-jdk-headless openjdk-19-jre-headless cmake vim-python-jedi clang sxiv mpv stow zathura zathura-pdf-poppler ripgrep aria2 libjs-prettify
